server:
  port: 443
  ssl:    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: easw409

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://lab.dja.kr:60105/dtmic?useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dtmic
    password: easw409
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
dtmic:
  admin-password: easw409